[mod]:add line numbers to all original files of nginx-1.24.0.tar.gz

diff --git a/nginx-1.24.0/auto/endianness b/nginx-1.24.0/auto/endianness
--- a/nginx-1.24.0/auto/endianness
+++ b/nginx-1.24.0/auto/endianness
@@ -1,50 +1,50 @@
-
-# Copyright (C) Igor Sysoev
-# Copyright (C) Nginx, Inc.
-
-
-echo $ngx_n "checking for system byte ordering ...$ngx_c"
-
-cat << END >> $NGX_AUTOCONF_ERR
-
-----------------------------------------
-checking for system byte ordering
-
-END
-
-
-cat << END > $NGX_AUTOTEST.c
-
-int main(void) {
-    int i = 0x11223344;
-    char *p;
-
-    p = (char *) &i;
-    if (*p == 0x44) return 0;
-    return 1;
-}
-
-END
-
-ngx_test="$CC $CC_TEST_FLAGS $CC_AUX_FLAGS \
-          -o $NGX_AUTOTEST $NGX_AUTOTEST.c $NGX_LD_OPT $ngx_feature_libs"
-
-eval "$ngx_test >> $NGX_AUTOCONF_ERR 2>&1"
-
-if [ -x $NGX_AUTOTEST ]; then
-    if $NGX_AUTOTEST >/dev/null 2>&1; then
-        echo " little endian"
-        have=NGX_HAVE_LITTLE_ENDIAN . auto/have
-    else
-        echo " big endian"
-    fi
-
-    rm -rf $NGX_AUTOTEST*
-
-else
-    rm -rf $NGX_AUTOTEST*
-
-    echo
-    echo "$0: error: cannot detect system byte ordering"
-    exit 1
-fi
+[1] 
+[2] # Copyright (C) Igor Sysoev
+[3] # Copyright (C) Nginx, Inc.
+[4] 
+[5] 
+[6] echo $ngx_n "checking for system byte ordering ...$ngx_c"
+[7] 
+[8] cat << END >> $NGX_AUTOCONF_ERR
+[9] 
+[10] ----------------------------------------
+[11] checking for system byte ordering
+[12] 
+[13] END
+[14] 
+[15] 
+[16] cat << END > $NGX_AUTOTEST.c
+[17] 
+[18] int main(void) {
+[19]     int i = 0x11223344;
+[20]     char *p;
+[21] 
+[22]     p = (char *) &i;
+[23]     if (*p == 0x44) return 0;
+[24]     return 1;
+[25] }
+[26] 
+[27] END
+[28] 
+[29] ngx_test="$CC $CC_TEST_FLAGS $CC_AUX_FLAGS \
+[30]           -o $NGX_AUTOTEST $NGX_AUTOTEST.c $NGX_LD_OPT $ngx_feature_libs"
+[31] 
+[32] eval "$ngx_test >> $NGX_AUTOCONF_ERR 2>&1"
+[33] 
+[34] if [ -x $NGX_AUTOTEST ]; then
+[35]     if $NGX_AUTOTEST >/dev/null 2>&1; then
+[36]         echo " little endian"
+[37]         have=NGX_HAVE_LITTLE_ENDIAN . auto/have
+[38]     else
+[39]         echo " big endian"
+[40]     fi
+[41] 
+[42]     rm -rf $NGX_AUTOTEST*
+[43] 
+[44] else
+[45]     rm -rf $NGX_AUTOTEST*
+[46] 
+[47]     echo
+[48]     echo "$0: error: cannot detect system byte ordering"
+[49]     exit 1
+[50] fi
diff --git a/nginx-1.24.0/auto/lib/perl/conf b/nginx-1.24.0/auto/lib/perl/conf
--- a/nginx-1.24.0/auto/lib/perl/conf
+++ b/nginx-1.24.0/auto/lib/perl/conf
@@ -1,83 +1,83 @@
-
-# Copyright (C) Igor Sysoev
-# Copyright (C) Nginx, Inc.
-
-
-echo "checking for perl"
-
-
-NGX_PERL_VER=`$NGX_PERL -v 2>&1 | grep '^This is perl' 2>&1 \
-                                | sed -e 's/^This is perl, \(.*\)/\1/'`
-
-if test -n "$NGX_PERL_VER"; then
-    echo " + perl version: $NGX_PERL_VER"
-
-    if [ "`$NGX_PERL -e 'use 5.008006; print "OK"'`" != "OK" ]; then
-        echo
-        echo "$0: error: perl 5.8.6 or higher is required"
-        echo
-
-        exit 1;
-    fi
-
-    if [ "`$NGX_PERL -MExtUtils::Embed -e 'print "OK"'`" != "OK" ]; then
-        echo
-        echo "$0: error: perl module ExtUtils::Embed is required"
-        echo
-
-        exit 1;
-    fi
-
-    NGX_PM_CFLAGS=`$NGX_PERL -MExtUtils::Embed -e ccopts`
-    NGX_PM_LDFLAGS=`$NGX_PERL -MConfig -e 'print $Config{lddlflags}'`
-
-    NGX_PERL_CFLAGS="$CFLAGS `$NGX_PERL -MExtUtils::Embed -e ccopts`"
-
-    # gcc 4.1/4.2 warn about unused values in pTHX_
-    NGX_PERL_CFLAGS=`echo $NGX_PERL_CFLAGS \
-                     | sed -e 's/-Wunused-value/-Wno-unused-value/'`
-    # icc8 warns 'declaration hides parameter "my_perl"' in ENTER and LEAVE
-    NGX_PERL_CFLAGS=`echo $NGX_PERL_CFLAGS \
-                     | sed -e 's/-wd171/-wd171 -wd1599/'`
-
-    ngx_perl_ldopts=`$NGX_PERL -MExtUtils::Embed -e ldopts`
-
-    ngx_perl_dlext=`$NGX_PERL -MConfig -e 'print $Config{dlext}'`
-    ngx_perl_libdir="src/http/modules/perl/blib/arch/auto"
-    ngx_perl_module="$ngx_perl_libdir/nginx/nginx.$ngx_perl_dlext"
-
-    if $NGX_PERL -V:usemultiplicity | grep define > /dev/null; then
-        have=NGX_HAVE_PERL_MULTIPLICITY . auto/have
-        echo " + perl interpreter multiplicity found"
-    fi
-
-    if $NGX_PERL -V:useithreads | grep undef > /dev/null; then
-        # FreeBSD port wants to link with -pthread non-threaded perl
-        ngx_perl_ldopts=`echo $ngx_perl_ldopts | sed 's/ -pthread//'`
-    fi
-
-    if [ "$NGX_SYSTEM" = "Darwin" ]; then
-        # OS X system perl wants to link universal binaries
-        ngx_perl_ldopts=`echo $ngx_perl_ldopts \
-                         | sed -e 's/-arch i386//' -e 's/-arch x86_64//'`
-    fi
-
-    if [ $USE_PERL = YES ]; then
-        CORE_LINK="$CORE_LINK $ngx_perl_ldopts"
-    fi
-
-    NGX_LIB_PERL="$ngx_perl_ldopts"
-
-    if test -n "$NGX_PERL_MODULES"; then
-        have=NGX_PERL_MODULES value="(u_char *) \"$NGX_PERL_MODULES\""
-        . auto/define
-        NGX_PERL_MODULES_MAN=$NGX_PERL_MODULES/man3
-    fi
-
-else
-    echo
-    echo "$0: error: perl 5.8.6 or higher is required"
-    echo
-
-    exit 1;
-fi
+[1] 
+[2] # Copyright (C) Igor Sysoev
+[3] # Copyright (C) Nginx, Inc.
+[4] 
+[5] 
+[6] echo "checking for perl"
+[7] 
+[8] 
+[9] NGX_PERL_VER=`$NGX_PERL -v 2>&1 | grep '^This is perl' 2>&1 \
+[10]                                 | sed -e 's/^This is perl, \(.*\)/\1/'`
+[11] 
+[12] if test -n "$NGX_PERL_VER"; then
+[13]     echo " + perl version: $NGX_PERL_VER"
+[14] 
+[15]     if [ "`$NGX_PERL -e 'use 5.008006; print "OK"'`" != "OK" ]; then
+[16]         echo
+[17]         echo "$0: error: perl 5.8.6 or higher is required"
+[18]         echo
+[19] 
+[20]         exit 1;
+[21]     fi
+[22] 
+[23]     if [ "`$NGX_PERL -MExtUtils::Embed -e 'print "OK"'`" != "OK" ]; then
+[24]         echo
+[25]         echo "$0: error: perl module ExtUtils::Embed is required"
+[26]         echo
+[27] 
+[28]         exit 1;
+[29]     fi
+[30] 
+[31]     NGX_PM_CFLAGS=`$NGX_PERL -MExtUtils::Embed -e ccopts`
+[32]     NGX_PM_LDFLAGS=`$NGX_PERL -MConfig -e 'print $Config{lddlflags}'`
+[33] 
+[34]     NGX_PERL_CFLAGS="$CFLAGS `$NGX_PERL -MExtUtils::Embed -e ccopts`"
+[35] 
+[36]     # gcc 4.1/4.2 warn about unused values in pTHX_
+[37]     NGX_PERL_CFLAGS=`echo $NGX_PERL_CFLAGS \
+[38]                      | sed -e 's/-Wunused-value/-Wno-unused-value/'`
+[39]     # icc8 warns 'declaration hides parameter "my_perl"' in ENTER and LEAVE
+[40]     NGX_PERL_CFLAGS=`echo $NGX_PERL_CFLAGS \
+[41]                      | sed -e 's/-wd171/-wd171 -wd1599/'`
+[42] 
+[43]     ngx_perl_ldopts=`$NGX_PERL -MExtUtils::Embed -e ldopts`
+[44] 
+[45]     ngx_perl_dlext=`$NGX_PERL -MConfig -e 'print $Config{dlext}'`
+[46]     ngx_perl_libdir="src/http/modules/perl/blib/arch/auto"
+[47]     ngx_perl_module="$ngx_perl_libdir/nginx/nginx.$ngx_perl_dlext"
+[48] 
+[49]     if $NGX_PERL -V:usemultiplicity | grep define > /dev/null; then
+[50]         have=NGX_HAVE_PERL_MULTIPLICITY . auto/have
+[51]         echo " + perl interpreter multiplicity found"
+[52]     fi
+[53] 
+[54]     if $NGX_PERL -V:useithreads | grep undef > /dev/null; then
+[55]         # FreeBSD port wants to link with -pthread non-threaded perl
+[56]         ngx_perl_ldopts=`echo $ngx_perl_ldopts | sed 's/ -pthread//'`
+[57]     fi
+[58] 
+[59]     if [ "$NGX_SYSTEM" = "Darwin" ]; then
+[60]         # OS X system perl wants to link universal binaries
+[61]         ngx_perl_ldopts=`echo $ngx_perl_ldopts \
+[62]                          | sed -e 's/-arch i386//' -e 's/-arch x86_64//'`
+[63]     fi
+[64] 
+[65]     if [ $USE_PERL = YES ]; then
+[66]         CORE_LINK="$CORE_LINK $ngx_perl_ldopts"
+[67]     fi
+[68] 
+[69]     NGX_LIB_PERL="$ngx_perl_ldopts"
+[70] 
+[71]     if test -n "$NGX_PERL_MODULES"; then
+[72]         have=NGX_PERL_MODULES value="(u_char *) \"$NGX_PERL_MODULES\""
+[73]         . auto/define
+[74]         NGX_PERL_MODULES_MAN=$NGX_PERL_MODULES/man3
+[75]     fi
+[76] 
+[77] else
+[78]     echo
+[79]     echo "$0: error: perl 5.8.6 or higher is required"
+[80]     echo
+[81] 
+[82]     exit 1;
+[83] fi
diff --git a/nginx-1.24.0/auto/lib/zlib/make b/nginx-1.24.0/auto/lib/zlib/make
--- a/nginx-1.24.0/auto/lib/zlib/make
+++ b/nginx-1.24.0/auto/lib/zlib/make
@@ -1,135 +1,135 @@
-
-# Copyright (C) Igor Sysoev
-# Copyright (C) Nginx, Inc.
-
-
-case "$NGX_CC_NAME" in
-
-    msvc)
-        ngx_makefile=makefile.msvc
-        ngx_opt="CPU_OPT=\"$CPU_OPT\" LIBC=$LIBC"
-        ngx_zlib="ZLIB=\"$ZLIB\""
-
-    ;;
-
-    owc)
-        ngx_makefile=makefile.owc
-        ngx_opt="CPU_OPT=\"$CPU_OPT\""
-        ngx_zlib=`echo ZLIB=\"$ZLIB\" | sed -e "s/\//$ngx_regex_dirsep/g"`
-    ;;
-
-    bcc)
-        ngx_makefile=makefile.bcc
-        ngx_opt="-DCPU_OPT=\"$CPU_OPT\""
-        ngx_zlib=`echo \-DZLIB=\"$ZLIB\" | sed -e "s/\//$ngx_regex_dirsep/g"`
-    ;;
-
-    *)
-        ngx_makefile=
-    ;;
-
-esac
-
-
-done=NO
-
-
-case "$NGX_PLATFORM" in
-
-    win32)
-
-        if [ -n "$ngx_makefile" ]; then
-            cat << END                                        >> $NGX_MAKEFILE
-
-`echo "$ZLIB/zlib.lib:	$NGX_MAKEFILE" | sed -e "s/\//$ngx_regex_dirsep/g"`
-	\$(MAKE) -f auto/lib/zlib/$ngx_makefile $ngx_opt $ngx_zlib
-
-END
-
-        else
-
-            cat << END                                        >> $NGX_MAKEFILE
-
-$ZLIB/libz.a:	$NGX_MAKEFILE
-	cd $ZLIB \\
-	&& \$(MAKE) distclean \\
-	&& \$(MAKE) -f win32/Makefile.gcc \\
-		CFLAGS="$ZLIB_OPT" CC="\$(CC)" \\
-		libz.a
-
-END
-
-        fi
-
-        done=YES
-    ;;
-
-    # FreeBSD: i386
-    # Linux: i686
-
-    *:i386 | *:i686)
-        case $ZLIB_ASM in
-            pentium)
-
-                cat << END                                    >> $NGX_MAKEFILE
-
-$ZLIB/libz.a:	$NGX_MAKEFILE
-	cd $ZLIB \\
-	&& \$(MAKE) distclean \\
-	&& cp contrib/asm586/match.S . \\
-	&& CFLAGS="$ZLIB_OPT -DASMV" CC="\$(CC)" \\
-		./configure \\
-	&& \$(MAKE) OBJA=match.o libz.a
-
-END
-
-                done=YES
-            ;;
-
-            pentiumpro)
-
-                cat << END                                    >> $NGX_MAKEFILE
-
-$ZLIB/libz.a:	$NGX_MAKEFILE
-	cd $ZLIB \\
-	&& \$(MAKE) distclean \\
-	&& cp contrib/asm686/match.S . \\
-	&& CFLAGS="$ZLIB_OPT -DASMV" CC="\$(CC)" \\
-		./configure \\
-	&& \$(MAKE) OBJA=match.o libz.a
-
-END
-
-                done=YES
-            ;;
-
-            NO)
-            ;;
-
-            *)
-                echo "$0: error: invalid --with-zlib-asm=$ZLIB_ASM option."
-                echo "The valid values are \"pentium\" and \"pentiumpro\" only".
-                echo
-
-                exit 1;
-            ;;
-        esac
-    ;;
-
-esac
-
-
-if [ $done = NO ]; then
-
-    cat << END                                                >> $NGX_MAKEFILE
-
-$ZLIB/libz.a:	$NGX_MAKEFILE
-	cd $ZLIB \\
-	&& \$(MAKE) distclean \\
-	&& CFLAGS="$ZLIB_OPT" CC="\$(CC)" \\
-		./configure \\
-	&& \$(MAKE) libz.a
-
-END
-
-fi
+[1] 
+[2] # Copyright (C) Igor Sysoev
+[3] # Copyright (C) Nginx, Inc.
+[4] 
+[5] 
+[6] case "$NGX_CC_NAME" in
+[7] 
+[8]     msvc)
+[9]         ngx_makefile=makefile.msvc
+[10]         ngx_opt="CPU_OPT=\"$CPU_OPT\" LIBC=$LIBC"
+[11]         ngx_zlib="ZLIB=\"$ZLIB\""
+[12] 
+[13]     ;;
+[14] 
+[15]     owc)
+[16]         ngx_makefile=makefile.owc
+[17]         ngx_opt="CPU_OPT=\"$CPU_OPT\""
+[18]         ngx_zlib=`echo ZLIB=\"$ZLIB\" | sed -e "s/\//$ngx_regex_dirsep/g"`
+[19]     ;;
+[20] 
+[21]     bcc)
+[22]         ngx_makefile=makefile.bcc
+[23]         ngx_opt="-DCPU_OPT=\"$CPU_OPT\""
+[24]         ngx_zlib=`echo \-DZLIB=\"$ZLIB\" | sed -e "s/\//$ngx_regex_dirsep/g"`
+[25]     ;;
+[26] 
+[27]     *)
+[28]         ngx_makefile=
+[29]     ;;
+[30] 
+[31] esac
+[32] 
+[33] 
+[34] done=NO
+[35] 
+[36] 
+[37] case "$NGX_PLATFORM" in
+[38] 
+[39]     win32)
+[40] 
+[41]         if [ -n "$ngx_makefile" ]; then
+[42]             cat << END                                        >> $NGX_MAKEFILE
+[43] 
+[44] `echo "$ZLIB/zlib.lib:	$NGX_MAKEFILE" | sed -e "s/\//$ngx_regex_dirsep/g"`
+[45] 	\$(MAKE) -f auto/lib/zlib/$ngx_makefile $ngx_opt $ngx_zlib
+[46] 
+[47] END
+[48] 
+[49]         else
+[50] 
+[51]             cat << END                                        >> $NGX_MAKEFILE
+[52] 
+[53] $ZLIB/libz.a:	$NGX_MAKEFILE
+[54] 	cd $ZLIB \\
+[55] 	&& \$(MAKE) distclean \\
+[56] 	&& \$(MAKE) -f win32/Makefile.gcc \\
+[57] 		CFLAGS="$ZLIB_OPT" CC="\$(CC)" \\
+[58] 		libz.a
+[59] 
+[60] END
+[61] 
+[62]         fi
+[63] 
+[64]         done=YES
+[65]     ;;
+[66] 
+[67]     # FreeBSD: i386
+[68]     # Linux: i686
+[69] 
+[70]     *:i386 | *:i686)
+[71]         case $ZLIB_ASM in
+[72]             pentium)
+[73] 
+[74]                 cat << END                                    >> $NGX_MAKEFILE
+[75] 
+[76] $ZLIB/libz.a:	$NGX_MAKEFILE
+[77] 	cd $ZLIB \\
+[78] 	&& \$(MAKE) distclean \\
+[79] 	&& cp contrib/asm586/match.S . \\
+[80] 	&& CFLAGS="$ZLIB_OPT -DASMV" CC="\$(CC)" \\
+[81] 		./configure \\
+[82] 	&& \$(MAKE) OBJA=match.o libz.a
+[83] 
+[84] END
+[85] 
+[86]                 done=YES
+[87]             ;;
+[88] 
+[89]             pentiumpro)
+[90] 
+[91]                 cat << END                                    >> $NGX_MAKEFILE
+[92] 
+[93] $ZLIB/libz.a:	$NGX_MAKEFILE
+[94] 	cd $ZLIB \\
+[95] 	&& \$(MAKE) distclean \\
+[96] 	&& cp contrib/asm686/match.S . \\
+[97] 	&& CFLAGS="$ZLIB_OPT -DASMV" CC="\$(CC)" \\
+[98] 		./configure \\
+[99] 	&& \$(MAKE) OBJA=match.o libz.a
+[100] 
+[101] END
+[102] 
+[103]                 done=YES
+[104]             ;;
+[105] 
+[106]             NO)
+[107]             ;;
+[108] 
+[109]             *)
+[110]                 echo "$0: error: invalid --with-zlib-asm=$ZLIB_ASM option."
+[111]                 echo "The valid values are \"pentium\" and \"pentiumpro\" only".
+[112]                 echo
+[113] 
+[114]                 exit 1;
+[115]             ;;
+[116]         esac
+[117]     ;;
+[118] 
+[119] esac
+[120] 
+[121] 
+[122] if [ $done = NO ]; then
+[123] 
+[124]     cat << END                                                >> $NGX_MAKEFILE
+[125] 
+[126] $ZLIB/libz.a:	$NGX_MAKEFILE
+[127] 	cd $ZLIB \\
+[128] 	&& \$(MAKE) distclean \\
+[129] 	&& CFLAGS="$ZLIB_OPT" CC="\$(CC)" \\
+[130] 		./configure \\
+[131] 	&& \$(MAKE) libz.a
+[132] 
+[133] END
+[134] 
+[135] fi
diff --git a/nginx-1.24.0/auto/os/solaris b/nginx-1.24.0/auto/os/solaris
--- a/nginx-1.24.0/auto/os/solaris
+++ b/nginx-1.24.0/auto/os/solaris
@@ -1,61 +1,61 @@
-
-# Copyright (C) Igor Sysoev
-# Copyright (C) Nginx, Inc.
-
-
-have=NGX_SOLARIS . auto/have_headers
-
-CORE_INCS="$UNIX_INCS"
-CORE_DEPS="$UNIX_DEPS $SOLARIS_DEPS"
-CORE_SRCS="$UNIX_SRCS $SOLARIS_SRCS "
-CORE_LIBS="$CORE_LIBS -lsocket -lnsl"
-
-NGX_RPATH=YES
-
-# Solaris's make does not support a blank line between target and rules
-ngx_spacer=
-
-CC_AUX_FLAGS="$CC_AUX_FLAGS -D_FILE_OFFSET_BITS=64 -lsocket -lnsl"
-
-
-if [ $ZLIB_ASM != NO ]; then
-    echo "$0: error: the --with-zlib-asm=CPU option is not supported"
-    echo "on that platform"
-    echo
-
-    exit 1
-fi
-
-
-ngx_feature="sendfilev()"
-ngx_feature_name="NGX_HAVE_SENDFILE"
-ngx_feature_run=no
-ngx_feature_incs="#include <sys/sendfile.h>"
-ngx_feature_path=
-ngx_feature_libs="-lsendfile"
-ngx_feature_test="int fd = 1; sendfilevec_t vec[1];
-                  size_t sent; ssize_t n;
-                  n = sendfilev(fd, vec, 1, &sent);
-                  if (n == -1) return 1"
-. auto/feature
-
-
-if [ $ngx_found = yes ]; then
-    CORE_SRCS="$CORE_SRCS $SOLARIS_SENDFILEV_SRCS"
-    CORE_LIBS="$CORE_LIBS -lsendfile"
-fi
-
-
-ngx_feature="event ports"
-ngx_feature_name="NGX_HAVE_EVENTPORT"
-ngx_feature_run=no
-ngx_feature_incs="#include <port.h>"
-ngx_feature_path=
-ngx_feature_libs=
-ngx_feature_test="(void) port_create()"
-. auto/feature
-
-if [ $ngx_found = yes ]; then
-    CORE_SRCS="$CORE_SRCS $EVENTPORT_SRCS"
-    EVENT_MODULES="$EVENT_MODULES $EVENTPORT_MODULE"
-fi
+[1] 
+[2] # Copyright (C) Igor Sysoev
+[3] # Copyright (C) Nginx, Inc.
+[4] 
+[5] 
+[6] have=NGX_SOLARIS . auto/have_headers
+[7] 
+[8] CORE_INCS="$UNIX_INCS"
+[9] CORE_DEPS="$UNIX_DEPS $SOLARIS_DEPS"
+[10] CORE_SRCS="$UNIX_SRCS $SOLARIS_SRCS "
+[11] CORE_LIBS="$CORE_LIBS -lsocket -lnsl"
+[12] 
+[13] NGX_RPATH=YES
+[14] 
+[15] # Solaris's make does not support a blank line between target and rules
+[16] ngx_spacer=
+[17] 
+[18] CC_AUX_FLAGS="$CC_AUX_FLAGS -D_FILE_OFFSET_BITS=64 -lsocket -lnsl"
+[19] 
+[20] 
+[21] if [ $ZLIB_ASM != NO ]; then
+[22]     echo "$0: error: the --with-zlib-asm=CPU option is not supported"
+[23]     echo "on that platform"
+[24]     echo
+[25] 
+[26]     exit 1
+[27] fi
+[28] 
+[29] 
+[30] ngx_feature="sendfilev()"
+[31] ngx_feature_name="NGX_HAVE_SENDFILE"
+[32] ngx_feature_run=no
+[33] ngx_feature_incs="#include <sys/sendfile.h>"
+[34] ngx_feature_path=
+[35] ngx_feature_libs="-lsendfile"
+[36] ngx_feature_test="int fd = 1; sendfilevec_t vec[1];
+[37]                   size_t sent; ssize_t n;
+[38]                   n = sendfilev(fd, vec, 1, &sent);
+[39]                   if (n == -1) return 1"
+[40] . auto/feature
+[41] 
+[42] 
+[43] if [ $ngx_found = yes ]; then
+[44]     CORE_SRCS="$CORE_SRCS $SOLARIS_SENDFILEV_SRCS"
+[45]     CORE_LIBS="$CORE_LIBS -lsendfile"
+[46] fi
+[47] 
+[48] 
+[49] ngx_feature="event ports"
+[50] ngx_feature_name="NGX_HAVE_EVENTPORT"
+[51] ngx_feature_run=no
+[52] ngx_feature_incs="#include <port.h>"
+[53] ngx_feature_path=
+[54] ngx_feature_libs=
+[55] ngx_feature_test="(void) port_create()"
+[56] . auto/feature
+[57] 
+[58] if [ $ngx_found = yes ]; then
+[59]     CORE_SRCS="$CORE_SRCS $EVENTPORT_SRCS"
+[60]     EVENT_MODULES="$EVENT_MODULES $EVENTPORT_MODULE"
+[61] fi
diff --git a/nginx-1.24.0/auto/types/sizeof b/nginx-1.24.0/auto/types/sizeof
--- a/nginx-1.24.0/auto/types/sizeof
+++ b/nginx-1.24.0/auto/types/sizeof
@@ -1,76 +1,76 @@
-
-# Copyright (C) Igor Sysoev
-# Copyright (C) Nginx, Inc.
-
-
-echo $ngx_n "checking for $ngx_type size ...$ngx_c"
-
-cat << END >> $NGX_AUTOCONF_ERR
-
-----------------------------------------
-checking for $ngx_type size
-
-END
-
-ngx_size=
-
-cat << END > $NGX_AUTOTEST.c
-
-#include <sys/types.h>
-#include <sys/time.h>
-$NGX_INCLUDE_UNISTD_H
-#include <signal.h>
-#include <stdio.h>
-#include <sys/resource.h>
-$NGX_INCLUDE_INTTYPES_H
-$NGX_INCLUDE_AUTO_CONFIG_H
-
-int main(void) {
-    printf("%d", (int) sizeof($ngx_type));
-    return 0;
-}
-
-END
-
-
-ngx_test="$CC $CC_TEST_FLAGS $CC_AUX_FLAGS \
-          -o $NGX_AUTOTEST $NGX_AUTOTEST.c $NGX_LD_OPT $ngx_feature_libs"
-
-eval "$ngx_test >> $NGX_AUTOCONF_ERR 2>&1"
-
-
-if [ -x $NGX_AUTOTEST ]; then
-    ngx_size=`$NGX_AUTOTEST`
-    echo " $ngx_size bytes"
-fi
-
-
-case $ngx_size in
-    4)
-        ngx_max_value=2147483647
-        ngx_max_len='(sizeof("-2147483648") - 1)'
-    ;;
-
-    8)
-        ngx_max_value=9223372036854775807LL
-        ngx_max_len='(sizeof("-9223372036854775808") - 1)'
-    ;;
-
-    *)
-        echo
-        echo "$0: error: can not detect $ngx_type size"
-
-        echo "----------"    >> $NGX_AUTOCONF_ERR
-        cat $NGX_AUTOTEST.c  >> $NGX_AUTOCONF_ERR
-        echo "----------"    >> $NGX_AUTOCONF_ERR
-        echo $ngx_test       >> $NGX_AUTOCONF_ERR
-        echo "----------"    >> $NGX_AUTOCONF_ERR
-
-        rm -rf $NGX_AUTOTEST*
-
-        exit 1
-esac
-
-
-rm -rf $NGX_AUTOTEST*
-
+[1] 
+[2] # Copyright (C) Igor Sysoev
+[3] # Copyright (C) Nginx, Inc.
+[4] 
+[5] 
+[6] echo $ngx_n "checking for $ngx_type size ...$ngx_c"
+[7] 
+[8] cat << END >> $NGX_AUTOCONF_ERR
+[9] 
+[10] ----------------------------------------
+[11] checking for $ngx_type size
+[12] 
+[13] END
+[14] 
+[15] ngx_size=
+[16] 
+[17] cat << END > $NGX_AUTOTEST.c
+[18] 
+[19] #include <sys/types.h>
+[20] #include <sys/time.h>
+[21] $NGX_INCLUDE_UNISTD_H
+[22] #include <signal.h>
+[23] #include <stdio.h>
+[24] #include <sys/resource.h>
+[25] $NGX_INCLUDE_INTTYPES_H
+[26] $NGX_INCLUDE_AUTO_CONFIG_H
+[27] 
+[28] int main(void) {
+[29]     printf("%d", (int) sizeof($ngx_type));
+[30]     return 0;
+[31] }
+[32] 
+[33] END
+[34] 
+[35] 
+[36] ngx_test="$CC $CC_TEST_FLAGS $CC_AUX_FLAGS \
+[37]           -o $NGX_AUTOTEST $NGX_AUTOTEST.c $NGX_LD_OPT $ngx_feature_libs"
+[38] 
+[39] eval "$ngx_test >> $NGX_AUTOCONF_ERR 2>&1"
+[40] 
+[41] 
+[42] if [ -x $NGX_AUTOTEST ]; then
+[43]     ngx_size=`$NGX_AUTOTEST`
+[44]     echo " $ngx_size bytes"
+[45] fi
+[46] 
+[47] 
+[48] case $ngx_size in
+[49]     4)
+[50]         ngx_max_value=2147483647
+[51]         ngx_max_len='(sizeof("-2147483648") - 1)'
+[52]     ;;
+[53] 
+[54]     8)
+[55]         ngx_max_value=9223372036854775807LL
+[56]         ngx_max_len='(sizeof("-9223372036854775808") - 1)'
+[57]     ;;
+[58] 
+[59]     *)
+[60]         echo
+[61]         echo "$0: error: can not detect $ngx_type size"
+[62] 
+[63]         echo "----------"    >> $NGX_AUTOCONF_ERR
+[64]         cat $NGX_AUTOTEST.c  >> $NGX_AUTOCONF_ERR
+[65]         echo "----------"    >> $NGX_AUTOCONF_ERR
+[66]         echo $ngx_test       >> $NGX_AUTOCONF_ERR
+[67]         echo "----------"    >> $NGX_AUTOCONF_ERR
+[68] 
+[69]         rm -rf $NGX_AUTOTEST*
+[70] 
+[71]         exit 1
+[72] esac
+[73] 
+[74] 
+[75] rm -rf $NGX_AUTOTEST*
+[76] 
diff --git a/nginx-1.24.0/auto/types/typedef b/nginx-1.24.0/auto/types/typedef
--- a/nginx-1.24.0/auto/types/typedef
+++ b/nginx-1.24.0/auto/types/typedef
@@ -1,82 +1,82 @@
-
-# Copyright (C) Igor Sysoev
-# Copyright (C) Nginx, Inc.
-
-
-echo $ngx_n "checking for $ngx_type ...$ngx_c"
-
-cat << END >> $NGX_AUTOCONF_ERR
-
-----------------------------------------
-checking for $ngx_type
-
-END
-
-ngx_found=no
-
-for ngx_try in $ngx_type $ngx_types
-do
-
-    cat << END > $NGX_AUTOTEST.c
-
-#include <sys/types.h>
-#include <signal.h>
-#include <sys/socket.h>
-#include <sys/time.h>
-#include <sys/resource.h>
-#include <netinet/in.h>
-$NGX_INCLUDE_INTTYPES_H
-
-int main(void) {
-    $ngx_try i = 0;
-    return (int) i;
-}
-
-END
-
-    ngx_test="$CC $CC_TEST_FLAGS $CC_AUX_FLAGS \
-              -o $NGX_AUTOTEST $NGX_AUTOTEST.c $NGX_LD_OPT $ngx_feature_libs"
-
-    eval "$ngx_test >> $NGX_AUTOCONF_ERR 2>&1"
-
-    if [ -x $NGX_AUTOTEST ]; then
-        if [ $ngx_try = $ngx_type ]; then
-            echo " found"
-            ngx_found=yes
-        else
-            echo ", $ngx_try used"
-            ngx_found=$ngx_try
-        fi
-    fi
-
-    if [ $ngx_found = no ]; then
-        if [ $ngx_try = $ngx_type ]; then
-            echo $ngx_n " $ngx_try not found$ngx_c"
-        else
-            echo $ngx_n ", $ngx_try not found$ngx_c"
-        fi
-
-        echo "----------"    >> $NGX_AUTOCONF_ERR
-        cat $NGX_AUTOTEST.c  >> $NGX_AUTOCONF_ERR
-        echo "----------"    >> $NGX_AUTOCONF_ERR
-        echo $ngx_test       >> $NGX_AUTOCONF_ERR
-        echo "----------"    >> $NGX_AUTOCONF_ERR
-    fi
-
-    rm -rf $NGX_AUTOTEST*
-
-    if [ $ngx_found != no ]; then
-        break
-    fi
-done
-
-if [ $ngx_found = no ]; then
-    echo
-    echo "$0: error: can not define $ngx_type"
-
-    exit 1
-fi
-
-if [ $ngx_found != yes ]; then
-    echo "typedef $ngx_found  $ngx_type;"   >> $NGX_AUTO_CONFIG_H
-fi
+[1] 
+[2] # Copyright (C) Igor Sysoev
+[3] # Copyright (C) Nginx, Inc.
+[4] 
+[5] 
+[6] echo $ngx_n "checking for $ngx_type ...$ngx_c"
+[7] 
+[8] cat << END >> $NGX_AUTOCONF_ERR
+[9] 
+[10] ----------------------------------------
+[11] checking for $ngx_type
+[12] 
+[13] END
+[14] 
+[15] ngx_found=no
+[16] 
+[17] for ngx_try in $ngx_type $ngx_types
+[18] do
+[19] 
+[20]     cat << END > $NGX_AUTOTEST.c
+[21] 
+[22] #include <sys/types.h>
+[23] #include <signal.h>
+[24] #include <sys/socket.h>
+[25] #include <sys/time.h>
+[26] #include <sys/resource.h>
+[27] #include <netinet/in.h>
+[28] $NGX_INCLUDE_INTTYPES_H
+[29] 
+[30] int main(void) {
+[31]     $ngx_try i = 0;
+[32]     return (int) i;
+[33] }
+[34] 
+[35] END
+[36] 
+[37]     ngx_test="$CC $CC_TEST_FLAGS $CC_AUX_FLAGS \
+[38]               -o $NGX_AUTOTEST $NGX_AUTOTEST.c $NGX_LD_OPT $ngx_feature_libs"
+[39] 
+[40]     eval "$ngx_test >> $NGX_AUTOCONF_ERR 2>&1"
+[41] 
+[42]     if [ -x $NGX_AUTOTEST ]; then
+[43]         if [ $ngx_try = $ngx_type ]; then
+[44]             echo " found"
+[45]             ngx_found=yes
+[46]         else
+[47]             echo ", $ngx_try used"
+[48]             ngx_found=$ngx_try
+[49]         fi
+[50]     fi
+[51] 
+[52]     if [ $ngx_found = no ]; then
+[53]         if [ $ngx_try = $ngx_type ]; then
+[54]             echo $ngx_n " $ngx_try not found$ngx_c"
+[55]         else
+[56]             echo $ngx_n ", $ngx_try not found$ngx_c"
+[57]         fi
+[58] 
+[59]         echo "----------"    >> $NGX_AUTOCONF_ERR
+[60]         cat $NGX_AUTOTEST.c  >> $NGX_AUTOCONF_ERR
+[61]         echo "----------"    >> $NGX_AUTOCONF_ERR
+[62]         echo $ngx_test       >> $NGX_AUTOCONF_ERR
+[63]         echo "----------"    >> $NGX_AUTOCONF_ERR
+[64]     fi
+[65] 
+[66]     rm -rf $NGX_AUTOTEST*
+[67] 
+[68]     if [ $ngx_found != no ]; then
+[69]         break
+[70]     fi
+[71] done
+[72] 
+[73] if [ $ngx_found = no ]; then
+[74]     echo
+[75]     echo "$0: error: can not define $ngx_type"
+[76] 
+[77]     exit 1
+[78] fi
+[79] 
+[80] if [ $ngx_found != yes ]; then
+[81]     echo "typedef $ngx_found  $ngx_type;"   >> $NGX_AUTO_CONFIG_H
+[82] fi
